version: '3.8'

services:
  # Service backend Spring Boot
  backend:
    image: gdxebec/skillup-backend:latest
    container_name: skillup-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/skillup?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_SERVLET_CONTEXT_PATH=/api
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - JWT_EXPIRATION=86400000
      - JWT_REFRESH_TOKEN_EXPIRATION=604800000
      - OPENROUTER_API_KEY=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
      - OPENROUTER_API_URL=https://openrouter.ai/api/v1
      - OPENROUTER_MODEL=google/gemma-3n-e4b-it:free
    depends_on:
      - db
    networks:
      - skillup-network

  # Service frontend Next.js (si vous avez un frontend séparé)
  frontend:
    image: gdxebec/skillup-frontend:latest  # Remplacer par votre image frontend ou utiliser un Dockerfile séparé
    container_name: skillup-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
    depends_on:
      - backend
    networks:
      - skillup-network

  # Service base de données MySQL (basé sur votre configuration application.yml)
  db:
    image: mysql:8.0
    container_name: skillup-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=skillup
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - skillup-network

networks:
  skillup-network:
    driver: bridge

volumes:
  mysql_data:
