/**
 * Carte de correspondance entre les emojis Unicode et leurs descriptions textuelles
 */
export const emojiMap: Record<string, string> = {
  "😀": "[sourire]",
  "😃": "[sourire]",
  "😄": "[sourire]",
  "😁": "[sourire]",
  "😆": "[rire]",
  "😅": "[rire]",
  "🤣": "[rire]",
  "😂": "[larmes de joie]",
  "🙂": "[sourire]",
  "🙃": "[sourire inversé]",
  "😉": "[clin d'œil]",
  "😊": "[sourire]",
  "😇": "[ange]",
  "🥰": "[amour]",
  "😍": "[amour]",
  "🤩": "[étoiles]",
  "😘": "[bisou]",
  "😗": "[bisou]",
  "☺️": "[sourire]",
  "😚": "[bisou]",
  "😙": "[bisou]",
  "🥲": "[sourire avec larme]",
  "😋": "[délicieux]",
  "😛": "[langue]",
  "😜": "[clin d'œil]",
  "🤪": "[fou]",
  "😝": "[langue]",
  "🤑": "[argent]",
  "🤗": "[câlin]",
  "🤭": "[surprise]",
  "🤫": "[chut]",
  "🤔": "[réfléchit]",
  "🤐": "[bouche fermée]",
  "🤨": "[sourcil levé]",
  "😐": "[neutre]",
  "😑": "[sans expression]",
  "😶": "[sans bouche]",
  "😏": "[sourire narquois]",
  "😒": "[pas impressionné]",
  "🙄": "[lève les yeux]",
  "😬": "[grimace]",
  "🤥": "[menteur]",
  "😌": "[soulagé]",
  "😔": "[pensif]",
  "😪": "[somnolent]",
  "🤤": "[bave]",
  "😴": "[endormi]",
  "😷": "[masque]",
  "🤒": "[malade]",
  "🤕": "[blessé]",
  "🤢": "[nauséeux]",
  "🤮": "[vomit]",
  "🤧": "[éternue]",
  "🥵": "[chaud]",
  "🥶": "[froid]",
  "🥴": "[étourdi]",
  "😵": "[étourdi]",
  "🤯": "[explosion]",
  "🤠": "[cowboy]",
  "🥳": "[fête]",
  "😎": "[cool]",
  "🤓": "[nerd]",
  "🧐": "[monocle]",
  "😕": "[confus]",
  "😟": "[inquiet]",
  "🙁": "[triste]",
  "☹️": "[triste]",
  "😮": "[surpris]",
  "😯": "[surpris]",
  "😲": "[choqué]",
  "😳": "[rougit]",
  "🥺": "[suppliant]",
  "😦": "[inquiet]",
  "😧": "[angoissé]",
  "😨": "[effrayé]",
  "😰": "[anxieux]",
  "😥": "[déçu]",
  "😢": "[pleure]",
  "😭": "[pleure]",
  "😱": "[crie]",
  "😖": "[frustré]",
  "😣": "[persévérant]",
  "😞": "[déçu]",
  "😓": "[sueur]",
  "😩": "[fatigué]",
  "😫": "[fatigué]",
  "🥱": "[bâille]",
  "😤": "[triomphant]",
  "😡": "[en colère]",
  "😠": "[en colère]",
  "🤬": "[juron]",
  "😈": "[diable]",
  "👿": "[diable]",
  "💀": "[crâne]",
  "☠️": "[crâne]",
  "💩": "[caca]",
  "🤡": "[clown]",
  "👹": "[monstre]",
  "👺": "[gobelin]",
  "👻": "[fantôme]",
  "👽": "[alien]",
  "👾": "[alien]",
  "🤖": "[robot]",
  "🎃": "[citrouille]",
  "😺": "[chat]",
  "😸": "[chat]",
  "😹": "[chat]",
  "😻": "[chat]",
  "😼": "[chat]",
  "😽": "[chat]",
  "🙀": "[chat]",
  "😿": "[chat]",
  "😾": "[chat]",
  "👋": "[salut]",
  "🤚": "[main]",
  "🖐️": "[main]",
  "✋": "[main]",
  "🖖": "[vulcain]",
  "👌": "[ok]",
  "🤌": "[geste italien]",
  "🤏": "[petit peu]",
  "✌️": "[victoire]",
  "🤞": "[doigts croisés]",
  "🤟": "[je t'aime]",
  "🤘": "[rock]",
  "🤙": "[appelle-moi]",
  "👈": "[gauche]",
  "👉": "[droite]",
  "👆": "[haut]",
  "🖕": "[doigt d'honneur]",
  "👇": "[bas]",
  "☝️": "[index]",
  "👍": "[pouce en haut]",
  "👎": "[pouce en bas]",
  "✊": "[poing]",
  "👊": "[poing]",
  "🤛": "[poing]",
  "🤜": "[poing]",
  "👏": "[applaudissements]",
  "🙌": "[hourra]",
  "👐": "[mains ouvertes]",
  "🤲": "[mains ouvertes]",
  "🤝": "[poignée de main]",
  "🙏": "[prière]",
  "✍️": "[écriture]",
  "💅": "[vernis]",
  "🤳": "[selfie]",
  "💪": "[biceps]",
  "🦾": "[bras mécanique]",
  "🦿": "[jambe mécanique]",
  "🦵": "[jambe]",
  "🦶": "[pied]",
  "👂": "[oreille]",
  "🦻": "[oreille]",
  "👃": "[nez]",
  "🧠": "[cerveau]",
  "🫀": "[cœur]",
  "🫁": "[poumons]",
  "🦷": "[dent]",
  "🦴": "[os]",
  "👀": "[yeux]",
  "👁️": "[œil]",
  "👅": "[langue]",
  "👄": "[bouche]",
  "💋": "[baiser]",
  "🩸": "[goutte de sang]",
  "❤️": "[cœur]",
  "🧡": "[cœur]",
  "💛": "[cœur]",
  "💚": "[cœur]",
  "💙": "[cœur]",
  "💜": "[cœur]",
  "🤎": "[cœur]",
  "🖤": "[cœur]",
  "🤍": "[cœur]",
  "💔": "[cœur brisé]",
  "❣️": "[cœur]",
  "💕": "[cœurs]",
  "💞": "[cœurs]",
  "💓": "[cœur]",
  "💗": "[cœur]",
  "💖": "[cœur]",
  "💘": "[cœur]",
  "💝": "[cœur]",
  "💟": "[cœur]",
  "♥️": "[cœur]",
  "💌": "[lettre d'amour]",
  "💤": "[sommeil]",
  "💢": "[colère]",
  "💣": "[bombe]",
  "💥": "[collision]",
  "💦": "[sueur]",
  "💨": "[vent]",
  "🕳️": "[trou]",
  "💫": "[étourdissement]",
  "💬": "[bulle]",
  "🗯️": "[bulle]",
  "💭": "[pensée]",
  "🔥": "[feu]",
  "❄️": "[flocon]",
  "🌟": "[étoile]",
  "⭐": "[étoile]",
  "🌠": "[étoile filante]",
  "🌈": "[arc-en-ciel]",
  "☀️": "[soleil]",
  "🌤️": "[soleil]",
  "⛅": "[soleil]",
  "🌥️": "[soleil]",
  "☁️": "[nuage]",
  "🌦️": "[pluie]",
  "🌧️": "[pluie]",
  "⛈️": "[orage]",
  "🌩️": "[éclair]",
  "🌨️": "[neige]",
  "☃️": "[bonhomme de neige]",
  "⛄": "[bonhomme de neige]",
  "🌬️": "[vent]",
  "💧": "[goutte]",
  "☔": "[parapluie]",
  "⚡": "[éclair]",
  "🔆": "[lumineux]",
  "🌊": "[vague]"
};
export const commonEmojis: { [key: string]: string } = {
  '😀': '[sourire]',
  '😃': '[sourire]',
  '😄': '[sourire]',
  '😁': '[sourire]',
  '😆': '[rire]',
  '😅': '[rire]',
  '🤣': '[rire]',
  '😂': '[larmes de joie]',
  '🙂': '[sourire]',
  '🙃': '[sourire inversé]',
  '😉': '[clin dœil]',
  '😊': '[sourire]',
  '😇': '[ange]',
  '🥰': '[amour]',
  '😍': '[amour]',
  '🤩': '[étoiles]',
  '😘': '[bisou]',
  '😗': '[bisou]',
  '☺️': '[sourire]',
  '😚': '[bisou]',
  '😙': '[bisou]',
  '🥲': '[sourire avec larme]',
  '😋': '[délicieux]',
  '😛': '[langue]',
  '😜': '[clin dœil]',
  '🤪': '[fou]',
  '😝': '[langue]',
  '🤑': '[argent]',
  '🤗': '[câlin]',
  '🤭': '[surprise]',
  '🤫': '[chut]',
  '🤔': '[réfléchit]',
  '🤐': '[bouche fermée]',
  '🤨': '[sourcil levé]',
  '😐': '[neutre]',
  '😑': '[sans expression]',
  '😶': '[sans bouche]',
  '😏': '[sourire narquois]',
  '😒': '[pas impressionné]',
  '🙄': '[lève les yeux]',
  '😬': '[grimace]',
  '🤥': '[menteur]',
  '😌': '[soulagé]',
  '😔': '[pensif]',
  '😪': '[somnolent]',
  '🤤': '[bave]',
  '😴': '[endormi]',
  '😷': '[masque]',
  '🤒': '[malade]',
  '🤕': '[blessé]',
  '🤢': '[nauséeux]',
  '🤮': '[vomit]',
  '🤧': '[éternue]',
  '🥵': '[chaud]',
  '🥶': '[froid]',
  '🥴': '[étourdi]',
  '😵': '[étourdi]',
  '🤯': '[explosion]',
  '🤠': '[cowboy]',
  '🥳': '[fête]',
  '😎': '[cool]',
  '🤓': '[nerd]',
  '🧐': '[monocle]',
  '😕': '[confus]',
  '😟': '[inquiet]',
  '🙁': '[triste]',
  '☹️': '[triste]',
  '😮': '[surpris]',
  '😯': '[surpris]',
  '😲': '[choqué]',
  '😳': '[rougit]',
  '🥺': '[suppliant]',
  '😦': '[inquiet]',
  '😧': '[angoissé]',
  '😨': '[effrayé]',
  '😰': '[anxieux]',
  '😥': '[déçu]',
  '😢': '[pleure]',
  '😭': '[pleure]',
  '😱': '[crie]',
  '😖': '[frustré]',
  '😣': '[persévérant]',
  '😞': '[déçu]',
  '😓': '[sueur]',
  '😩': '[fatigué]',
  '😫': '[fatigué]',
  '🥱': '[bâille]',
  '😤': '[triomphant]',
  '😡': '[en colère]',
  '😠': '[en colère]',
  '🤬': '[juron]',
  '😈': '[diable]',
  '👿': '[diable]',
  '💀': '[crâne]',
  '☠️': '[crâne]',
  '💩': '[caca]',
  '🤡': '[clown]',
  '👹': '[monstre]',
  '👺': '[gobelin]',
  '👻': '[fantôme]',
  '👽': '[alien]',
  '👾': '[alien]',
  '🤖': '[robot]',
  '🎃': '[citrouille]',
  '😺': '[chat]',
  '😸': '[chat]',
  '😹': '[chat]',
  '😻': '[chat]',
  '😼': '[chat]',
  '😽': '[chat]',
  '🙀': '[chat]',
  '😿': '[chat]',
  '😾': '[chat]',
  '👋': '[salut]',
  '🤚': '[main]',
  '🖐️': '[main]',
  '✋': '[main]',
  '🖖': '[vulcain]',
  '👌': '[ok]',
  '🤌': '[geste italien]',
  '🤏': '[petit peu]',
  '✌️': '[victoire]',
  '🤞': '[doigts croisés]',
  '🤟': '[je taime]',
  '🤘': '[rock]',
  '🤙': '[appelle-moi]',
  '👈': '[gauche]',
  '👉': '[droite]',
  '👆': '[haut]',
  '🖕': '[doigt dhonneur]',
  '👇': '[bas]',
  '☝️': '[index]',
  '👍': '[pouce en haut]',
  '👎': '[pouce en bas]',
  '✊': '[poing]',
  '👊': '[poing]',
  '🤛': '[poing]',
  '🤜': '[poing]',
  '👏': '[applaudissements]',
  '🙌': '[hourra]',
  '👐': '[mains ouvertes]',
  '🤲': '[mains ouvertes]',
  '🤝': '[poignée de main]',
  '🙏': '[prière]',
  '✍️': '[écriture]',
  '💅': '[vernis]',
  '🤳': '[selfie]',
  '💪': '[biceps]',
  '🦾': '[bras mécanique]',
  '🦿': '[jambe mécanique]',
  '🦵': '[jambe]',
  '🦶': '[pied]',
  '👂': '[oreille]',
  '🦻': '[oreille]',
  '👃': '[nez]',
  '🧠': '[cerveau]',
  '🫀': '[cœur]',
  '🫁': '[poumons]',
  '🦷': '[dent]',
  '🦴': '[os]',
  '👀': '[yeux]',
  '👁️': '[œil]',
  '👅': '[langue]',
  '👄': '[bouche]',
  '💋': '[baiser]',
  '🩸': '[goutte de sang]',
  '❤️': '[cœur]',
  '🧡': '[cœur]',
  '💛': '[cœur]',
  '💚': '[cœur]',
  '💙': '[cœur]',
  '💜': '[cœur]',
  '🤎': '[cœur]',
  '🖤': '[cœur]',
  '🤍': '[cœur]',
  '💔': '[cœur brisé]',
  '❣️': '[cœur]',
  '💕': '[cœurs]',
  '💞': '[cœurs]',
  '💓': '[cœur]',
  '💗': '[cœur]',
  '💖': '[cœur]',
  '💘': '[cœur]',
  '💝': '[cœur]',
  '💟': '[cœur]',
  '♥️': '[cœur]',
  '💌': '[lettre damour]',
  '💤': '[sommeil]',
  '💢': '[colère]',
  '💣': '[bombe]',
  '💥': '[collision]',
  '💦': '[sueur]',
  '💨': '[vent]',
  '🕳️': '[trou]',
  '💫': '[étourdissement]',
  '💬': '[bulle]',
  '🗯️': '[bulle]',
  '💭': '[pensée]',
  '🔥': '[feu]',
  '❄️': '[flocon]',
  '🌟': '[étoile]',
  '⭐': '[étoile]',
  '🌠': '[étoile filante]',
  '🌈': '[arc-en-ciel]',
  '☀️': '[soleil]',
  '🌤️': '[soleil]',
  '⛅': '[soleil]',
  '🌥️': '[soleil]',
  '☁️': '[nuage]',
  '🌦️': '[pluie]',
  '🌧️': '[pluie]',
  '⛈️': '[orage]',
  '🌩️': '[éclair]',
  '🌨️': '[neige]',
  '☃️': '[bonhomme de neige]',
  '⛄': '[bonhomme de neige]',
  '🌬️': '[vent]',
  '💧': '[goutte]',
  '☔': '[parapluie]',
  '⚡': '[éclair]',
  '🔆': '[lumineux]',
  '🌊': '[vague]',
  '📘': '[Livre]',
  '✅': '[OK]',
  '🧱': '[Structure]',
  '🧩': '[Puzzle]',
  '🧪': '[Test]',
  '📅': '[Date]',
  '✏️': '[Edit]',
  '📝': '[Note]',
}